export const GET_CURRENT_PRODUCT_START = 'GET_CURRENT_PRODUCT_START';
export const GET_CURRENT_PRODUCT_SUCCESS = 'GET_CURRENT_PRODUCT_SUCCESS';
export const GET_CURRENT_PRODUCT_FAILED = 'GET_CURRENT_PRODUCT_FAILED';
export const GET_CURRENT_RELATED_PRODUCTS_START = 'GET_CURRENT_RELATED_PRODUCTS_START';
export const GET_CURRENT_RELATED_PRODUCTS_SUCCESS = 'GET_CURRENT_RELATED_PRODUCTS_SUCCESS';
export const GET_CURRENT_RELATED_PRODUCTS_FAILED = 'GET_CURRENT_RELATED_PRODUCTS_FAILED';